# This Actions file will update the vaccine progress on a schedule each day
name: updateplots
on:
  schedule:
    - cron: '30 14,22 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Run R script
        run: Rscript progress.R
      - name: Commit results
        run: |
          git config --global user.email "trevor.tombe@gmail.com"
          git config --global user.name "Trevor Tombe"
          git add 'Plots/*.png'
          git commit -m "Update All Plots" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
